spring.application.name=smartcrm-backend

spring.security.user.name=admin
spring.security.user.password=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/smartcrm
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mysupersecretkeymysupersecretkey12345
jwt.expiration=3600000